version: 2

updates:
  - package-ecosystem: sbt
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    labels:
      - dependencies
    commit-message:
      prefix: build(deps)
    groups:
      sbt-all:
        applies-to: version-updates
        patterns: ["*"]
        update-types:
          - major
          - minor
          - patch
      sbt-security:
        applies-to: security-updates
        patterns: ["*"]
