version = "3.11.5"
runner.dialect = scala3
runner.dialectOverride.allowSignificantIndentation = false
rewrite.scala3.removeOptionalBraces = no
rewrite.scala3.convertToNewSyntax = false
lineEndings = unix
maxColumn = 100
newlines.topLevelBodyIfMinStatements = [before,after]
newlines.topLevelBodyMinStatements = 2
newlines.avoidForSimpleOverflow=[slc, tooLong]
newlines.topLevelStatementBlankLines = [
  {
    blanks = 1,
    minBreaks = 1,
    regex = "^(?!((Term\\.Apply)|(Defn\\.Object)))"
  }
]

align.preset = most
align.multiline = false
align.tokens."+" = [
  {
    code = ":=", owner = "Term.ApplyInfix"
  },
  {
    code = "+=", owner = "Term.ApplyInfix"
  },
  {
    code = "++=", owner = "Term.ApplyInfix"
  },
  {
    code = "--=", owner = "Term.ApplyInfix"
  },
  {
    code = "-=", owner = "Term.ApplyInfix"
  }
]

docstrings.style = "SpaceAsterisk"
docstrings.wrap = yes
docstrings.blankFirstLine = yes
docstrings.oneline = unfold

rewrite.rules = [
  AvoidInfix, # Avoid infix calls (except for operators)
  RedundantBraces,
  RedundantParens, # Ensure redundant parentheses are removed
  SortModifiers, # Ensure modifiers like `implicit` or `final` are sorted the same
  PreferCurlyFors, # Replaces parentheses into curly braces in for comprehensions that contain multiple enumerator generators
  Imports
]

rewrite.sortModifiers.order = [
  "private", "protected", "final", "sealed", "abstract", "override",
  "implicit", "inline", "transparent", "opaque", "open", "infix", "erased", "lazy"
]

rewrite.redundantBraces.maxLines = 1
rewrite.redundantBraces.stringInterpolation = true

rewrite.imports.sort = original
rewrite.imports.groups = [
  ["java\\..*"],
  ["scala\\..*"],
  ["cats\\..*", "fs2\\..*"]
]

rewrite.trailingCommas.style = never

project.includePaths = ["glob:**.scala", "glob:**.sbt", "glob:**.sc", "glob:**.md"]
project.excludePaths = ["glob:**metals.sbt"]
